Organisms: SmallModal, MediumModal, LargeModal (Implemented as <AdminModal size={"small" | "medium" | "large"}/>)
uwblueprint/pregnancy-centre pull request #111
Opened 2021-04-08 22:11 UTC by chamod-gamage

**Work Done:**

+ Further abstracted our modal component hierarchy: CommonModal --> AuthModal --> SignInModal, SignUpModal, etc.; AdminModal --> CreateRequest(''/Type/Group), etc. (future)
+ Created AdminModal which supports three sizes (props.size = "small" or "medium" or "large") according to the Notion tickets/[Figma](https://www.figma.com/file/dcSbJOfK3Jg1gCpWOd6hAK/TPC-Employee-Experience%3A-Phase-1?node-id=761%3A5675)
  + [SmallModal](https://www.notion.so/uwblueprintexecs/Organism-SmallModal-dc7a3259aaec4cc686670590f78a2a43)
![image](https://user-images.githubusercontent.com/41309709/114102626-a3c3cf80-9895-11eb-8c4c-01c4dd6675cc.png)
  + [MediumModal](https://www.notion.so/uwblueprintexecs/Organism-MediumModal-6cb948bda87f4202b37005d2bdf4e28b)
![image](https://user-images.githubusercontent.com/41309709/114102657-b938f980-9895-11eb-829b-648bc669bdae.png)
  + [LargeModal](https://www.notion.so/uwblueprintexecs/Organism-LargeModal-88d649bf56a5480f811e94f77c1507c4)
![image](https://user-images.githubusercontent.com/41309709/114102693-cc4bc980-9895-11eb-973e-cfa0e331522c.png)

2021-04-09 00:25 UTC, meganniu requested changes
Great work Chamod!!

Styling nits:
+ "X" buttons should be black
+ Font weight of headers should be 600
+ There are some headers that include more than text. Is there some way we can accomodate this? example:
![Screenshot from 2021-04-08 19-59-25](https://user-images.githubusercontent.com/20423590/114110224-05d80100-98a5-11eb-9725-1fbf42cb619d.png)

2021-04-09 00:25 UTC, meganniu commented on client/src/App.tsx
> +          <Route path='/adminmodal' strict component={() => <AdminModal size="large" title="Create Type" handleClose={() => { console.log("HI") }} show >Create Type</AdminModal>}></Route>
Note for other reviewers: there's a duplicate route for '/signup', so it's OK to remove '/signup' on line 19

2021-04-09 00:25 UTC, meganniu commented on client/src/components/organisms/AdminModal.tsx
> +const AdminModal: FunctionComponent<Props> = (props: Props) => {
Could we change the name of this component to `FormModal`?

2021-04-09 00:25 UTC, meganniu commented on client/src/components/organisms/AuthModal.tsx
> +const AuthModal: FunctionComponent<Props> = (props: Props) => {
Could we change the name of this component to `LogoModal`?

2021-04-09 00:25 UTC, meganniu commented on client/src/components/organisms/Modal.tsx
> +  const modalSize: "sm" | "lg" | "xl" = props.size === "small" ? "sm" : props.size === "medium" ? "lg" : "xl"
Could we use switch cases for this translation? LOL i think itll be more readable than nested ternary

2021-04-09 00:25 UTC, meganniu commented on client/src/components/organisms/Modal.tsx
> +      {props.size !== "default" ?
We could deduplicate some html by returning the following
```
<Modal show={props.show} onHide={props.handleClose} centered={true} className={props.class} size={props.size === "default" ? undefined : modalSize} dialogClassName="border-radius-12">
  <Modal.Header closeButton={!props.customClose} className={`${props.class}-header` + (props.size === "default" ? "" : `-${props.size}`)} >{props.header}{props.customClose && <i onClick={props.handleClose} className={`bi bi-x ${props.class}-header close` + (props.size === "default" ? "" : ` ${props.size}`)}></i>}</Modal.Header>
  <Modal.Body>{props.children}</Modal.Body>
  <Modal.Footer />
</Modal>
```

2021-04-09 00:45 UTC, chamod-gamage reviewed
> Great work Chamod!!
> 
> Styling nits:
> 
> * "X" buttons should be black
> * Font weight of headers should be 600
> * There are some headers that include more than text. Is there some way we can accomodate this? example:
>   ![Screenshot from 2021-04-08 19-59-25](https://user-images.githubusercontent.com/20423590/114110224-05d80100-98a5-11eb-9725-1fbf42cb619d.png)

@meganniu Since every FormModal includes a left-aligned title (from what I can tell) can I include an additional prop in FormModal (typed as React.ReactNode) called extraHeader that basically takes in any JSX in cases like these?

2021-04-09 00:45 UTC, chamod-gamage commented on client/src/App.tsx
> -          <Route path='/signup' strict component={SignUpModal}></Route>
this /signup route was a duplicate btw so i guess we'll remove it in this pr

2021-04-09 00:49 UTC, guy-ro approved these changes
LGTM

imo, if the sizing was done through setting the class of the outermost div in Modal.tsx to the class described in the prop "size", this would be cleaner

2021-04-09 00:49 UTC, guy-ro commented on client/src/App.tsx
> +          <Route path='/adminmodal' strict component={() => <AdminModal size="medium" title="Create Request" handleClose={() => { console.log("HI") }} show ><></></AdminModal>}></Route>
Remove this before merging.

2021-04-09 00:49 UTC, guy-ro commented on client/src/components/organisms/AdminModal.tsx
> +const AdminModal: FunctionComponent<Props> = (props: Props) => {
What makes this distinct from CommonModal? I don't really see anything that CommonModal can't do? The only thing different that I can see is the "hr". We can simply add an option (a boolean prop) for an "hr" in this position in CommonModal. Just making sure we really need this modal done as a separate component?

2021-04-09 00:49 UTC, guy-ro commented on client/src/components/organisms/AdminModal.tsx
> +    <CommonModal customClose class="modal-admin" size={props.size} show={props.show} handleClose={props.handleClose} header={<><div className={`modal-admin-header-title-${props.size}`}>
Don't need `<>` around the div inside header

2021-04-09 00:49 UTC, guy-ro commented on client/src/components/organisms/Modal.tsx
> +  const modalSize: "sm" | "lg" | "xl" = props.size === "small" ? "sm" : props.size === "medium" ? "lg" : "xl"
Or instead, can we just do this through css? The size prop can be a className and the style associated with each size can be done in CommonModal.scss

2021-04-09 03:01 UTC, chamod-gamage commented
@meganniu @guy-ro Thx for your reviews :)
I've covered all of the fixes you guys brought up and all that's left is further discussion of the necessity of the component. My opinion is that maybe the work itself wasn't super necessary but now that we have the component we might as well use it since it only makes it easier down the line to plug in the Modal Body contents for the Admin Forms.

2021-04-10 03:24 UTC, meganniu approved these changes
Looks great :)))) Thanks @chamod-gamage

2021-04-10 15:51 UTC, merged