Richtextfield
uwblueprint/pregnancy-centre pull request #122
Opened 2021-04-11 05:24 UTC by guy-ro

This ended up being super complicated and filled with logic. Apologies in advance for reviewers. (there is a very good reason Github uses markdown). 

To fully understand the code, unfortunately a foundation in Draft.js is useful- contact me if needed! I've added comments for most things a quick dive into Draft.js wouldn't bring up.

**ADDED:**
- Draft.js module to client. Chosen instead of Quill.js for customizability and ease of using with "sanitation".
- RichTextField component (read and write). Supports bold input with a button and key commands. Supports unordered list input with a button and key commands
- RichTextDisplay component (read only, for rendering rich text created by using RichTextField)

**MODIFIED:**
- Seeder now uses the Draft.js format (thus database has requestGroup.description in the correct format)
- RequestGroupDonorView now shows descriptions for requestGroups using RichTextDisplay
- InfoBox modified to have children (so we can easily use RichTextDisplay)
- Moved a bunch of colors around in _config.scss to better reflect how we are using them

2021-04-11 17:07 UTC, bonnie-chin commented
Wowowow damn okay going the extra mile with Draft.js 😤 thank y'all sm for your work omg 

Some design feedback :D
- Just a lil confused abt the situation here -- after the field goes into its error state the text should be #333333 once they start typing in there 
![image](https://user-images.githubusercontent.com/57274622/114313948-ac4f1c80-9ac6-11eb-9ee5-af8e33d732de.png)

- Super small thing, but I think there's smth up here with the double outline (both a rounded grey box and an unrounded red box)
![image](https://user-images.githubusercontent.com/57274622/114313902-8295f580-9ac6-11eb-8942-5e037a721c94.png)

2021-04-11 17:08 UTC, bonnie-chin reviewed
Wowowow damn okay going the extra mile with Draft.js 😤 thank y'all sm for your work omg 

Some design feedback :D
- Just a lil confused abt the situation here -- after the field goes into its error state the text should be #333333 once they start typing in there 
![image](https://user-images.githubusercontent.com/57274622/114313948-ac4f1c80-9ac6-11eb-9ee5-af8e33d732de.png)

- Super small thing, but I think there's smth up here with the double outline (both a rounded grey box and an unrounded red box)
![image](https://user-images.githubusercontent.com/57274622/114313902-8295f580-9ac6-11eb-8942-5e037a721c94.png)

2021-04-11 17:24 UTC, guy-ro commented
Thanks @bonnie-chin ! Removed the double border

2021-04-11 17:25 UTC, guy-ro commented
@meganniu regarding

> Some design feedback :D
> 
> * Just a lil confused abt the situation here -- after the field goes into its error state the text should be #333333 once they start typing in there

Should the user of RichTextField set isErroneous to false on change? Or should RichTextField do taht?

2021-04-11 18:05 UTC, meganniu commented
@guy-ro 

> Should the user of RichTextField set isErroneous to false on change? Or should RichTextField do taht?

User of RichTextField should be changing isErroneous

2021-04-11 19:51 UTC, meganniu requested changes
Just a few comments, but otherwise looks amazing 🤩🤩
thanks for ur hard work @guy-ro!

2021-04-11 19:51 UTC, meganniu commented on client/src/components/atoms/RichTextField.tsx
> +            props.onChange(JSON.stringify(convertToRaw(state.getCurrentContent())));
I think we need to pass an empty string to props.onChange here
The logic on line 65 and 16 rely on props.initialContent to be falsy/an empty string

2021-04-11 19:51 UTC, meganniu commented on client/src/components/atoms/RichTextField.tsx
> +            setEditorState(EditorState.createWithContent(ContentState.createFromText(props.defaultText)))
I think creating new content means we lose all the history and the user can't undo actions
I'd suggest:
```
llet state = EditorState.createWithContent(ContentState.createFromText(props.defaultText))
if(props.initialContent){
   cosnt tempState = EditorState.createWithContent(convertFromRaw(JSON.parse(props.initialContent)))
   if (tempState.getCurrentContent().hasText()){
    state =  tempState
   } 
}

const [editorState, setEditorState] = React.useState(state) 

function onChange(state: EditorState) {
        // ...

        if (active && !state.getCurrentContent().hasText()) {
            props.onChange(JSON.stringify(convertToRaw(state.getCurrentContent())));
            add props.defaultText to state
            setEditorState(state)
            setActive(false)
            return
        }

        // ...
    }
```
but there are probably better ways to do this

2021-04-11 20:00 UTC, guy-ro commented
BUG: Empty -> list doesn't work

2021-04-11 20:08 UTC, meganniu approved these changes
LGTM!!!

2021-04-11 20:08 UTC, meganniu commented on client/src/components/atoms/RichTextField.tsx
> +            props.onChange(JSON.stringify(convertToRaw(state.getCurrentContent())));
nvrm

2021-04-11 21:53 UTC, guy-ro commented
@meganniu bugs are fixed

- history is kept on erasing all content
- making a list when content is empty now works

The solution was simple - don't use Draft.js for default text :)

2021-04-11 21:54 UTC, guy-ro commented on client/src/components/atoms/RichTextField.tsx
> +            setEditorState(EditorState.createWithContent(ContentState.createFromText(props.defaultText)))
fixed

2021-04-11 23:35 UTC, meganniu commented
Sweet, everything LGTM!

2021-04-12 14:29 UTC, Anand-Issac approved these changes
Good work, lgtm

2021-04-12 15:55 UTC, merged