Send email for password reset
uwblueprint/pregnancy-centre pull request #128
Opened 2021-04-12 02:59 UTC by meganniu

### Changes
+ Moved html for `PasswordResetEmailSentModal` to `SendResetPasswordEmailModal`
  + Show the html for `PasswordResetEmailSentModal` if password reset email is sent in `SendResetPasswordEmailModal.tsx`
  + Deleted `PasswordResetEmailSentModal.tsx`
+ Added auth function to send password reset modal

### Screenshots
![Screenshot from 2021-04-11 22-55-00](https://user-images.githubusercontent.com/20423590/114334708-260ff600-9b19-11eb-9566-719972d1792c.png)
![Screenshot from 2021-04-11 22-56-15](https://user-images.githubusercontent.com/20423590/114334715-29a37d00-9b19-11eb-8876-876f460766ce.png)
![Screenshot from 2021-04-11 22-55-44](https://user-images.githubusercontent.com/20423590/114334717-29a37d00-9b19-11eb-89d6-b22498535a9b.png)
![Screenshot from 2021-04-11 22-55-29](https://user-images.githubusercontent.com/20423590/114334719-2a3c1380-9b19-11eb-98a8-1b524e3d44dc.png)

### Demo
https://user-images.githubusercontent.com/20423590/114333958-9158c880-9b17-11eb-9a17-b77290cbbd05.mov

2021-04-12 20:34 UTC, chamod-gamage approved these changes
Few nitpicks but otherwise lgtm!

2021-04-12 20:34 UTC, chamod-gamage commented on client/src/pages/SendResetPasswordEmailModal.tsx
> +              If your email is registered we’ll  send a password reset link to the email address below where you can set a new password.
Nit: extra space - "we'll" + "  " + " " + "send"

2021-04-12 20:34 UTC, chamod-gamage commented on client/src/pages/SendResetPasswordEmailModal.tsx
> +        </span >
Nit: Incosistent whitespace inside html tags

2021-04-12 20:34 UTC, chamod-gamage commented on client/src/services/auth.ts
> +}
Nit: Unnecessary whitespace at the end here

2021-04-13 00:52 UTC, azissac requested changes
Shouldn't the X days be changed after email is sent

2021-04-13 00:52 UTC, azissac commented on client/src/pages/SendResetPasswordEmailModal.tsx
> +              The link will expire after X days, after which you’ll have to request another reset link.
Change X days

2021-04-13 00:56 UTC, bonnie-chin commented
Design ✅ approved 😄

2021-04-13 00:56 UTC, bonnie-chin approved these changes

2021-04-13 01:02 UTC, azissac approved these changes
Lgtm :))

2021-04-13 01:03 UTC, Anand-Issac approved these changes
lgtm :))

2021-04-13 03:59 UTC, merged