Donor Homepage Top Carousel 🎠
uwblueprint/pregnancy-centre pull request #196
Opened 2021-07-05 03:53 UTC by bonnie-chin

**Work Done:**
- Added links to new homepage images and testimonials into DonorHomepageConfig
- Centered homepage text
- Added carousel 😎

**Things to Double Check:**
- Handling of responsiveness (I tried using Col but [to my knowledge] I'd then have to create 2 additional empty Cols, I felt like that was a cluttered way of handling it?)
- Hierarchy of CSS

**Images:**
Large Screen:
![image](https://user-images.githubusercontent.com/57274622/124415212-64850d80-dd22-11eb-8af5-2cbaf02f9ce1.png)

Mobile/Narrow:
![image](https://user-images.githubusercontent.com/57274622/124415461-e5440980-dd22-11eb-97e8-ab812f1c7480.png)

2021-07-10 00:58 UTC, meganniu requested changes
WOW look at u blasting thru ur tasks
thanks for the amazing work @bonnie-chin 🤩🤩

Left a few comments + the branch needs to be merged/rebased
lmk if you have any questions!

2021-07-10 00:58 UTC, meganniu commented on client/src/components/organisms/HomepageBanner.tsx
> +    <div className="col-md-6 homepage-banner-info">
Could  we move the banner text overlay into the `BannerCarousel` component?

2021-07-10 00:58 UTC, meganniu commented on client/src/components/atoms/style/BannerCarousel.scss
> +    & img {
nit: remove `& `  before `img` because it's implicit
```
.banner-carousel {
  #...
  img {
    #...
  }
}
```

2021-07-11 01:18 UTC, meganniu requested changes
Some files to remove

2021-07-11 01:18 UTC, meganniu commented on client/src/components/molecules/ClientRequestTable.tsx
> +import { gql, useMutation } from "@apollo/client";
Delete file

2021-07-11 01:18 UTC, meganniu commented on client/src/components/organisms/AdminRequestClientBrowser.tsx
> +import { Dropdown, Spinner } from "react-bootstrap";
Delete file

2021-07-11 01:18 UTC, meganniu commented on client/src/pages/AdminClientView.tsx
>  import React, { FunctionComponent } from "react";
Delete file

2021-07-13 02:11 UTC, kevinwang2040 commented on .vscode/extensions.json
> +{
dont think this file should be included.

2021-07-18 01:07 UTC, meganniu requested changes
Thanks for addressing the comments!

2021-07-18 01:07 UTC, meganniu commented on client/src/components/atoms/BannerCarousel.tsx
> +    const bannerImgs = DonorHomepageConfig.Banner;
Read the `DonorHomepageConfig` in a wrapper component for `BannerCarousel`
Then pass data (image urls, banner text) to `BannerCarousel`

We want to make `BannerCarousel` reusable

2021-07-18 01:07 UTC, meganniu commented on client/src/components/atoms/BannerCarousel.tsx
> +        <div className="homepage-banner">
Change `className` to match the name of the component. In the future, if someone creates a component called `HomepageBanner`, then they can use the css class `homepage-banner`
```
<div className="banner-carousel">
```

2021-07-18 01:07 UTC, meganniu commented on client/src/components/atoms/BannerCarousel.tsx
> +                <h1>Help women and families in Kitchener-Waterloo thrive with your donation today</h1>
The text for the banner should be stored in `DonorHomepageConfig`

2021-07-18 01:07 UTC, meganniu commented on client/src/components/molecules/ClientRequestTable.tsx
> +import { gql, useMutation } from "@apollo/client";
Delete file please

2021-07-18 01:07 UTC, meganniu commented on client/src/components/molecules/RequestsTable.tsx
> +        console.log("hoi");
stray console.log

ctrl+f for console.logs your diffs on github before request review to avoid comments like this

2021-07-18 01:07 UTC, meganniu commented on client/src/pages/DonorHomepage.tsx
> +                    <BannerCarousel />
Make a wrapper for `BannerCarousel` that reads `DonorHomepageConfig` and use it here instead of `BannerCarousel`

2021-07-27 00:33 UTC, meganniu approved these changes
NIcely done @bonnie-chin ! 
Left some nits, but once they're addressed you should be good to go 🏁🏁

2021-07-27 00:33 UTC, meganniu commented on client/src/config/donorHomepageConfig.json
> +  "Banner": {
nit: use lowercase `banner`

2021-07-27 00:33 UTC, meganniu commented on client/src/config/donorHomepageConfig.json
> +  "Testimonials": [
nit: use lowercase `testimonials`

2021-07-27 00:33 UTC, meganniu commented on client/src/components/organisms/Banner.tsx
> +const Banner: FunctionComponent = () => {
nit: call the component `DonorHomepageBanner` or `HomepageBanner` so no one thinks it's a generic banner component

2021-07-27 00:33 UTC, meganniu commented on client/src/components/atoms/BannerCarousel.tsx
> +    bannerIntv: number;
nit: remove "banner" prefix and use full names
```
images: Array<string>;
header: string;
description: string;
transitionInterval: number;
```

2021-07-27 00:33 UTC, meganniu commented on client/src/components/atoms/BannerCarousel.tsx
> +                            <img src={`${imgLink}`} />
nit: just use the variable without string interpolation
```
<img src={imgLink} />
```

2021-07-27 00:33 UTC, meganniu commented on client/src/components/atoms/style/BannerCarousel.scss
> +    &-info {
width of text overlay needs to a bit larger

figma:
![Screenshot from 2021-07-26 20-30-28](https://user-images.githubusercontent.com/20423590/127076199-8960c3a8-2929-40a7-b6ec-efbb8a26fa20.png)


current implementation at 1440px:
![Screenshot from 2021-07-26 20-28-56](https://user-images.githubusercontent.com/20423590/127076163-312b6fa9-2be4-45f5-814b-eca88b671e3f.png)

2021-08-01 19:53 UTC, merged