Add confirmation modal and supporting files
uwblueprint/pregnancy-centre pull request #47
Opened 2021-03-07 21:39 UTC by jlight99

Test by running the app and navigating to http://localhost:3000/confirmation
Also, see screenshot below:
![confirmationModal](https://user-images.githubusercontent.com/33968239/110255778-71a41280-7f63-11eb-82c2-eb88b3bd3c14.png)

NOTE: Modal.tsx, Modal.scss, and tpc-leaf.png are all being added in a different PR (https://github.com/uwblueprint/pregnancy-centre/pull/45) which should be merged before this one. These 3 files don't belong in this PR, but they are currently included so that reviewers can checkout this branch, run the code, and see the confirmation modal working. Once PR#45 has been merged, I will merge in main again which will remove the 3 files from this PR.

2021-03-08 00:42 UTC, chamod-gamage requested changes
Should be good once these changes are covered~

2021-03-08 00:42 UTC, chamod-gamage commented on client/src/pages/ConfirmationModal.tsx
> +  const [email, setEmail] = useState(props.email);
We're not modifying the email in this component at all right? If so, I'd replace with 
```
const {email} = props
```

2021-03-08 00:42 UTC, chamod-gamage commented on client/src/pages/ConfirmationModal.tsx
> +function ConfirmationModal(props: any) {
I think we should type the component like we do in SampleComponent.tsx

2021-03-08 00:42 UTC, chamod-gamage commented on client/src/components/organisms/Modal.tsx
> +function CommonModal(props: any) {
I think we should type the component like we do in SampleComponent.tsx

2021-03-08 00:42 UTC, chamod-gamage commented on client/src/components/organisms/Modal.tsx
> +import { useDispatch } from "react-redux";
Don't think we need to import the stuff in the curly braces since they're not used in the rest of the component

2021-03-08 00:42 UTC, chamod-gamage commented on client/src/components/organisms/Modal.tsx
> +import { Button, Modal } from 'react-bootstrap';
Don't need to import Button here

2021-03-08 00:42 UTC, chamod-gamage commented on client/src/pages/ConfirmationModal.tsx
> +  const handleShow = () => setShow(true);
This function doesn't seem to be used in the component

2021-03-11 23:55 UTC, meganniu approved these changes
LGTM!!!! thnx again :))

2021-03-11 23:55 UTC, meganniu commented on client/src/App.tsx
> +        {/* TODO: delete /confirmation endpoint after logic for triggering the confirmation modal upon signup has been added */}
could you leave your username next to the TODO comment (something like `TODO(jlight99):...`) so we know who to talk to if we have questions

2021-03-14 19:17 UTC, chamod-gamage approved these changes
LGTM! Thx for getting all of the changes in~

2021-03-14 19:18 UTC, merged